# Generated by Django 5.2.3 on 2025-06-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('ask', 'Ask')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='folder',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('ask', 'Ask')], default='private', max_length=10),
        ),
    ]
